name: Compilar ejecutable
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Compilar Proyecto
      run: |
        dotnet new console -o MiProyecto
        xcopy /y "antivirus - 副本.cs" MiProyecto\Program.cs
        cd MiProyecto
        dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true -o ../resultado

    - name: Guardar ejecutable
      uses: actions/upload-artifact@v4
      with:
        name: Antivirus-EXE
        path: resultado/MiProyecto.exe
